version: "2"
services:
  mysql:
    container_name: mysql
    image: mysql:8
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=MySQL8IsGreat!
      - MYSQL_USER=whatabook_user
      - MYSQL_PASSWORD=MySQL8IsGreat!
    ports:
      - 33306:3306
    volumes:
      - ./whatabook-initdb.d/:/docker-entrypoint-initdb.d/