version: "2" 
services: 
  mysql:
    container_name: mysql
    image: mysql:8
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=sqlpass
      - MYSQL_PASSWORD=sqlpass
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=pysports_user
    ports:
      - 3306:3306
    
